apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/component: "deployment"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Release.Name }}

          {{- $taggedImage := printf "%s:%s" .Values.runnerImage .Values.runnerTag }}
          image: {{ $taggedImage }}

          securityContext:
            privileged: {{ .Values.privileged }}

          resources:
            limits:
              memory: {{ .Values.memoryLimit }}
              cpu: {{ .Values.cpuLimit }}


          env:
            - name: GITHUB_OWNER
              value: {{ required ".Values.githubOwner must be set." .Values.githubOwner }}
            - name: GITHUB_REPOSITORY
              value: {{ .Values.githubRepository }}
            - name: RUNNER_LABELS
              value: {{ $taggedImage }},{{- range .Values.runnerLabels }}{{trim .}},{{- end}}
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: {{ .Values.secretKey }}
            # Any injected env values from values.yaml will go below
              {{- range .Values.runnerEnv }}
            - name: {{ .name }}
              value: {{ .value }}
        {{- end }}
          # Enable custom cluster PKI
          # https://docs.openshift.com/container-platform/4.6/networking/configuring-a-custom-pki.html
          {{ if .Values.clusterPKI }}
          volumeMounts: 
            - name: trusted-ca
              mountPath: /etc/pki/ca-trust/extracted/pem
              readOnly: true 
          {{ end }}   

      # Enable custom cluster PKI - Volumes
      {{ if .Values.clusterPKI }}
      volumes: 
        - name: trusted-ca
          configMap:
            name: trusted-ca
            items:
              - key: ca-bundle.crt 
                path: tls-ca-bundle.pem 
      {{end}}
