name: Helm Lint
on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:

env:
  CHART_DIR: actions-runner

jobs:
  helm_lint:
    name: Helm Lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: helm lint ${{ env.CHART_DIR }}
